### ISSUE TITLE
麻烦测试一下 spp里面举例的腾讯云速度

### ISSUE THREAD

**Issue by chmis8000** [esrrhs/connperf#1]
1.麻烦您测试一下 spp里面举例的国内腾讯云速度，connperf帮助举例的是国内国外速度对比。
2.我测试 我自己的腾讯云， tcp、ricmp都可以，rudp、quic、kcp 不通。tcp基本满速，ricmp只有可怜的不到1M速度，是否正常？
./connperf -l :7777 -p tcp -read
./connperf -l 0.0.0.0 -p ricmp -read
./connperf -l :7777 -p rudp -read
./connperf -l :7777 -p quic -read
./connperf -l :7777 -p kcp -read
windows:
.\connperf -s 123.53.122.173:7777 -p tcp -write
.\connperf -s 123.53.122.173 -p ricmp -write
.\connperf -s 123.53.122.173:7777 -p rudp -write
.\connperf -s 123.53.122.173:7777 -p quic -write
.\connperf -s 123.53.122.173:7777 -p kcp -write

**Comment by esrrhs** [comment]
rudp、quic、kcp 不通，应该是udp包没通，看看腾讯云的网络安全组是不是没有打开udp

**Comment by chmis8000** [comment]
感谢，确实是 安全组，不仅腾讯没开，linux的也没开udp。
我测试 国内访问国内腾讯云，速度最好的是 tcp和quick协议， kcp、rudp不稳且略低，最低的是ricmp不到0.7M平均速度。

**Comment by esrrhs** [comment]
嗯 国内访问国内，肯定是tcp最优，试试跨国的，因为丢包率高，tcp就完蛋了
